// Evidence bundle loader. Two on-disk formats, one in-memory Bundle:
//   v3  generated by `verify-fix bundle` (manifest.json + check/ + recordings/ + results/ + rca.json)
//   v2  the verifier's own seeded fixtures (hand-written manifest + check/); scenes carry a `mode`
// Nothing in a bundle drives the target by itself: the scene layer reads each
// scene's `mode` and shapes traffic at the proxy (src/scene/proxy.ts).

import { readFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import type { ApiRecording, Bundle, BundleConfig, Scene } from "./types.ts";
import type { ManifestV3 } from "./bundle/types.ts";
import { parseCheckConfig } from "./scene/config-diff.ts";
import { parseMode } from "./scene/modes.ts";

export interface LoadedBundle {
  bundle: Bundle;
}

const CONFIG_FILE = "checkly.config.ts";

function readTree(dir: string): Record<string, string> {
  const out: Record<string, string> = {};
  if (!existsSync(dir)) return out;
  const walk = (d: string) => {
    for (const name of readdirSync(d)) {
      const p = join(d, name);
      if (statSync(p).isDirectory()) walk(p);
      else out[relative(dir, p).split("\\").join("/")] = readFileSync(p, "utf8");
    }
  };
  walk(dir);
  return out;
}

function validateScenes(scenes: Scene[], where: string): void {
  for (const s of scenes) {
    const m = parseMode(s.mode);
    if (m.kind === "unknown") throw new Error(`${where}: scene ${s.sceneId}: ${m.reason}`);
  }
}

export function loadBundle(dirIn: string): LoadedBundle {
  const dir = resolve(dirIn);
  const manifestPath = join(dir, "manifest.json");
  if (!existsSync(manifestPath)) throw new Error(`bundle manifest not found: ${manifestPath}`);
  const raw = JSON.parse(readFileSync(manifestPath, "utf8")) as Record<string, unknown>;
  const files = readTree(join(dir, "check"));
  const configFile = files[CONFIG_FILE] !== undefined ? CONFIG_FILE : null;

  if (raw.schemaVersion === "v3") return { bundle: fromV3(raw as unknown as ManifestV3, dir, files, configFile) };
  if (raw.schemaVersion !== "v2") throw new Error(`unsupported bundle schemaVersion: ${String(raw.schemaVersion)}`);

  const bundle = raw as unknown as Bundle;
  const checkPath = join(dir, "check", bundle.check.file);
  if (!existsSync(checkPath)) throw new Error(`check source for "${bundle.check.file}" not found at ${checkPath}`);
  bundle.checkSource = readFileSync(checkPath, "utf8");
  bundle.files = files;
  bundle.configFile = configFile;
  bundle.config = (raw.config as BundleConfig | undefined) ?? (configFile ? configFromSource(files[configFile]) : null);
  bundle.recordedOrigin = (raw.recordedOrigin as string | undefined) ?? null;
  bundle.dir = dir;
  bundle.playwright = null;
  validateScenes(bundle.scenes, manifestPath);
  return { bundle };
}

/** BundleConfig from a checkly.config.ts text (seeded bundles have no API document). */
export function configFromSource(source: string): BundleConfig | null {
  const view = parseCheckConfig(source);
  if (view.runParallel === null && view.locations === null) return null;
  return {
    runParallel: view.runParallel ?? false,
    locations: view.locations ?? [],
    frequencyMinutes: view.frequency && /^\d+$/.test(view.frequency) ? Number(view.frequency) : null,
    environmentVariables: view.envKeys,
  };
}

function readApiRecording(dir: string, file: string | null | undefined): ApiRecording | null {
  if (!file) return null;
  const absolute = join(dir, file);
  if (!existsSync(absolute)) return null;
  return JSON.parse(readFileSync(absolute, "utf8")) as ApiRecording;
}

function fromV3(m: ManifestV3, dir: string, files: Record<string, string>, configFile: string | null): Bundle {
  const file = m.check.file ?? m.check.files[0] ?? null;
  if (!file) throw new Error(`${dir}: v3 manifest names no check file`);
  const checkSource = files[file];
  if (checkSource === undefined) throw new Error(`${dir}: check source "${file}" missing under check/`);
  const scenes: Scene[] = m.scenes.map((s) => ({
    sceneId: s.sceneId,
    type: s.type,
    state: s.state,
    mode: s.mode,
    alternativeMode: s.alternativeMode,
    environment: s.environment,
    verdict: s.verdict,
    experiments: s.experiments,
    assertionsInvolved: s.assertionsInvolved,
    notes: s.notes,
  }));
  validateScenes(scenes, join(dir, "manifest.json"));
  const seq = m.determinism.sequential;
  const ovl = m.determinism.overlap;
  const bundle: Bundle = {
    schemaVersion: "v3",
    incidentId: m.incidentId,
    incident: { title: m.incident.title, description: m.incident.description, sourceReference: m.incident.sourceReference ?? undefined },
    check: { repo: m.check.repo ?? "", file, name: m.check.name, checkType: m.check.checkType, logicalId: m.check.logicalId ?? "", deployedId: m.check.deployedId },
    checkSource,
    files,
    configFile,
    config: {
      runParallel: m.config.runParallel,
      locations: m.config.locations,
      frequencyMinutes: m.config.frequencyMinutes,
      environmentVariables: m.config.environmentVariables.map((e) => e.key),
    },
    recordedOrigin: m.target.recordedOrigin,
    dir,
    playwright: m.config.playwright?.configPath
      ? { configFile: m.config.playwright.configPath.replace(/^\.\//, ""), projects: m.config.playwright.projects }
      : null,
    api: m.check.checkType === "API"
      ? { failing: readApiRecording(dir, m.recordings.apiFailing), passing: readApiRecording(dir, m.recordings.apiPassing) }
      : null,
    scenes,
    envAssumptions: m.envAssumptions,
    // PR-7: without measured numbers the gate stays closed (UNCERTAIN, never PASS).
    // A concurrency incident needs both a green one-at-a-time baseline and a
    // red overlap. A persistent live incident (such as check drift) needs the
    // original check to fail every time in `live`; an overlap number is not
    // relevant to that incident.
    determinism: (() => {
      const reproduction = scenes.find((s) => s.type === "REPRODUCTION");
      const mode = parseMode(reproduction?.mode);
      const isConcurrent = mode.kind === "live-concurrent";
      const achieved = !m.determinism.measured
        ? 0
        : isConcurrent
          ? Math.min(seq?.runs ?? 0, ovl?.pairs ?? 0)
          : seq?.runs ?? 0;
      return {
        targetRuns: 20,
        achieved,
        sequentialPassRate: seq?.passRate ?? 0,
        overlapFailRate: ovl?.failRate ?? 0,
        reproductionFailRate: isConcurrent ? ovl?.failRate ?? 0 : seq ? Number((1 - seq.passRate).toFixed(3)) : 0,
        baselinePassRate: isConcurrent ? seq?.passRate ?? 0 : null,
        method: m.determinism.method ?? null,
        lastVerifiedAt: m.determinism.lastVerifiedAt,
      };
    })(),
    runBudget: m.runBudget,
    oracleProvenance: m.oracleProvenance,
  };
  return bundle;
}
